# Generated by Django 6.0.1 on 2026-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('rate', models.FloatField()),
                ('is_free', models.BooleanField(default=True)),
            ],
        ),
    ]
